config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :dashboard, :groups, :categories, :products, :menus
    devise_for :users, class_name: "Admin::User", controllers: {
      confirmations: "admin/users/confirmations",
      passwords: "admin/users/passwords",
      registrations: "admin/users/registrations",
      sessions: "admin/users/sessions", 
      unlocks: "admin/users/unlocks"       
    }
    root 'dashboard#index'
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions", 
    unlocks: "users/unlocks"       
  }
  
  resources :site do
    collection do
      get 'find'
      post 'spec'
      post 'cart_add'
      post 'cart_del'
    end

    member do
    end
  end

  resources :search

  resources :shopping

  resources :myaccount

  root 'site#index'

end

app/views/admin/common/_footer.html.erb
<div id="footer">
	copyright
</div>

app/views/admin/common/_navbar.html.erb
<div class="ui fixed inverted menu">
	<div id="sidemenu" class="item">
		<a href="#"><i class="sidebar icon large"></i><span>選單</span></a>
	</div>
	<div class="ui container">
		<%=
			content_tag(:a, class: "header item", href: admin_dashboard_index_path) do
				concat(image_tag("logo.png", class: "logo"))
				concat(content_tag(:span, "Fragrence"))
			end
		%>
		<% menus = current_admin_user.menus.where("(
			admin_menus_users.parent_id IS NULL
				or
			admin_menus_users.parent_id =0)
				and
			admin_menus_users.position='top'") %>
		<% menus.each do |sub| %>
		<%= g_nav_menu sub %>
		<% end %>
	</div>
	<div class="ui right dropdown item">
		<i class="user icon"></i>
		<%= current_admin_user.username %>
		<i class="dropdown icon"></i>
		<div class="menu">
			<div class="item">基本資料</div>
			<%= link_to('修改密碼', edit_admin_user_registration_path, :class => :item) %>
			<%= link_to('登出', destroy_admin_user_session_path, :method => :delete, :class => :item) %>
		</div>
	</div>
</div>

app/views/admin/common/_sidebar.html.erb
<div class="ui sidebar inverted vertical accordion menu">
	<div class="item">
		<h3>SourceCode</h3>
	</div>
	<% menus = current_admin_user.menus.where("(
		admin_menus_users.parent_id IS NULL
			or
		admin_menus_users.parent_id =0)
			and
		admin_menus_users.position='side'") %>
	<% menus.each do |sub| %>
	<%= g_side_menu sub %>
	<% end %>
</div>