config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :dashboard, :groups, :categories, :products, :menus
    devise_for :users, class_name: "Admin::User", controllers: {
      confirmations: "admin/users/confirmations",
      passwords: "admin/users/passwords",
      registrations: "admin/users/registrations",
      sessions: "admin/users/sessions", 
      unlocks: "admin/users/unlocks"       
    }
    root 'dashboard#index'
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions", 
    unlocks: "users/unlocks"       
  }
  
  resources :site do
    collection do
      get 'find'
      post 'spec'
      post 'cart_add'
      post 'cart_del'
    end

    member do
    end
  end

  resources :search

  resources :shopping

  resources :myaccount

  root 'site#index'

end

app/models/admin/product.rb
class Admin::Product < ActiveRecord::Base
	validates :caption, :itemcode, presence: true

	has_many :main_pictures, -> { order(:seq) }, class_name: "Admin::ProductMainPicture", dependent: :destroy
	accepts_nested_attributes_for :main_pictures, allow_destroy: true, :reject_if => lambda { |a| a[:image].blank? }

	has_many :profile_pictures, -> { order(:seq) }, class_name: "Admin::ProductProfilePicture", dependent: :destroy
	accepts_nested_attributes_for :profile_pictures, allow_destroy: true, :reject_if => lambda { |a| a[:image].blank? }
	#
	has_many :categories, through: :category_products
	has_many :category_products, dependent: :destroy
	#
	has_many :sub_products, -> { order(:seq) }, foreign_key: "product_id", dependent: :destroy
	accepts_nested_attributes_for :sub_products, allow_destroy: true, :reject_if => lambda { |a| (a[:size].blank? && a[:color].blank?) || a[:qty].blank?}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  # 
  before_action :set_record, :only => [:show, :edit, :update, :destroy]

  def index
    @products_grid = initialize_grid(Admin::Product.all, per_page: 15)
  end

  def new
    @product = Admin::Product.new
  end

  def create
    @product = Admin::Product.create(product_params)
    if @product.save
      flash[:notice] = '新增成功'
      redirect_to :action => 'index'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
      # 圖片在存檔時沒有更新seq欄位, 在找到解決方案前, 先手動方式處理
      if !params[:admin_product][:main_pictures_attributes].nil?
        params[:admin_product][:main_pictures_attributes].each do |k, v|
          Admin::ProductMainPicture.find(v[:id]).update_attribute(:seq, v[:seq]) unless !Admin::ProductMainPicture.exists?(:id => v[:id])
        end
      end

      # 圖片在存檔時沒有更新seq欄位, 在找到解決方案前, 先手動方式處理
      if !params[:admin_product][:profile_pictures_attributes].nil?
        params[:admin_product][:profile_pictures_attributes].each do |k, v|
          Admin::ProductProfilePicture.find(v[:id]).update_attribute(:seq, v[:seq]) unless !Admin::ProductProfilePicture.exists?(:id => v[:id])
        end
      end

      flash[:notice] = '修改成功'
      redirect_to :action => 'index'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:notice] = '刪除成功'
    redirect_to :action => 'index'
  end

private

  def set_record
    @product = Admin::Product.find(params[:id])
  end

  def product_params
    params.require(:admin_product).permit(:id, :caption, :description, :unit_price, :sale_price, :cost, :itemcode, 
      {sub_products_attributes: [:id, :size, :color, :qty, :itemcode, :seq, :_destroy]}, 
      {main_pictures_attributes: [:id, :image_cache, :image, :seq, :_destroy]},
      {profile_pictures_attributes: [:id, :image_cache, :image, :seq, :_destroy]},
      category_ids:[]
    )
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_category_fields.html.erb
<% if !f.sub_categories.empty? %>
  <div class="eight wide column">
    <h5 class="ui top attached header">
      <div class="ui checkbox">
        <%= check_box_tag "admin_product[category_ids][]", f.id, @product.categories.include?(f) %>
        <label><h5 class="ui blue header"><i class="bookmark icon"></i><%= f.caption %></h5></label>
      </div>
    </h5>
    <div class="ui attached segment">
      <% if !f.sub_categories.empty? %>
        <div class="ui grid">
          <% f.sub_categories.each do |sub| %>
            <div class="four wide column">
              <div class="ui checkbox">
                <%= check_box_tag "admin_product[category_ids][]", sub.id, @product.categories.include?(sub) %>
                <label><%= sub.caption %></label> 
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="eight wide column">
    <div class="ui attached segment">
      <div class="ui checkbox">
        <%= check_box_tag "admin_product[category_ids][]", f.id, @product.categories.include?(f) %>
        <label><h5 class="ui blue header"><i class="bookmark icon"></i><%= f.caption %></h5></label>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/_form.html.erb
<script>
//
  function readURL(input) {
    img = $(input).siblings('img');
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
      img
        .attr('src', e.target.result)
        .width(70)
        .height(70);
      };

      reader.readAsDataURL(input.files[0]);
    }
  }

  $(function(){
    $('.ui.sticky')
      .sticky({
        offset       : 60,
        context: '.ui.green.segment'
      })
    ;
  });
</script>
<%= simple_form_for @product do |f| %>
  <div class="ui green segment">
    <div class="ui clearing">
      <h4 class="ui red huge left floated header"><%= @product.new_record? ? "新增" : "修改" %>商品</h4>
      <div class="ui buttons right floated sticky">
        <%= link_to "取消", :back, class: "ui button" %>
        <div class="or"></div>
        <%= f.button :submit, "保存", :disable_with => "Submiting..."%>
      </div>
    </div>
  	<div class="field">
  		<label>基本資料</label>
  		<div class="four fields">
  		  <%= f.input :caption, wrapper: :input_labeled, label: "商品名稱", placeholder: "商品名稱", required: true  %>
  		  <%= f.input :itemcode, wrapper: :input_labeled, label: "商店貨號", placeholder: "商店貨號", required: true  %>
  		</div>
  	</div>
    <div class="field">
      <label>價格設定</label>
      <div class="five fields">
        <%= f.input :unit_price, wrapper: :input_labeled, label: "定價", placeholder: "定價", input_html: { min: 0 } %>
        <%= f.input :sale_price, wrapper: :input_labeled, label: "售價", placeholder: "售價", input_html: { min: 0 }  %>
        <%= f.input :cost, wrapper: :input_labeled, label: "成本", placeholder: "成本", input_html: { min: 0 } %>
      </div>
    </div>
    <div class="field">
      <label>商品說明</label>
      <div class="fields">
        <div class="ui sixteen wide field">
        <%= f.input :description, :as => :ckeditor, placeholder: "商品說明",
            input_html:{
              :ckeditor => {
                :toolbar => 'Full',
                :language => 'zh',
                :autoGrow_onStartup => false,
                :extraPlugins => 'autogrow,smiley',
              }
            } %>
            <!-- app/assets/javascripts/ckeditor/reinit.js -->
        </div>
      </div>
    </div>
    <div class="field">
      <h4 class="ui horizontal divider"> 分類設定 </h4>
      <div class="ui grid">
        <%= hidden_field_tag "admin_product[category_ids][]", nil %>
        <% for category in Admin::Category.all.where("(parent_id IS NULL or parent_id =0)") %>
          <%= render 'category_fields', f: category %>
        <% end %>
      </div>
    </div>
    <div class="field">
      <h4 class="ui horizontal divider header"> 產品圖片 </h4>
      <%= link_to_add_association '新增', f, :main_pictures, partial: 'picture_fields',
          "data-association-insertion-node": '.sorting_panel.picture',
          "data-association-insertion-method": :append,
          class: "ui green button",
          style: "float:right" %>
          <!-- data-association-insertion-method # :append or :prepend -->

      <div style="clear:both;"></div>
      <div class="sorting_panel picture ui grid">
      <!-- nested form從這裡開始 -->
      <%= f.simple_fields_for :main_pictures do |sub| %>
        <%= render 'picture_fields', f: sub %>
      <% end %>
      <!-- nested form結束 -->
      </div>
    </div>
    <div style="clear:both;"></div>
  	<div class="field">
      <h4 class="ui horizontal divider header"> 子商品 </h4>
  		<%= link_to_add_association '新增', f, :sub_products, partial: 'product_fields',
  				"data-association-insertion-node": '.sorting_panel.item',
  				"data-association-insertion-method": :append,
          class: "ui green button",
          style: "float:right" %>
          <!-- data-association-insertion-method # :append or :prepend -->

      <div style="clear:both;"></div>
  		<div class="sorting_panel item">
  	  <!-- nested form從這裡開始 -->
      <%= f.simple_fields_for :sub_products do |sub| %>
        <%= render 'product_fields', f: sub %>
      <% end %>
  	  <!-- nested form結束 -->
  	  </div>
  	</div>
    <div style="clear:both;"></div>
    <div class="field">
      <h4 class="ui horizontal divider header"> 說明圖片 </h4>
      <%= link_to_add_association '新增', f, :profile_pictures, partial: 'profile_fields',
          "data-association-insertion-node": '.sorting_panel.profile',
          "data-association-insertion-method": :append,
          class: "ui green button",
          style: "float:right" %>
          <!-- data-association-insertion-method # :append or :prepend -->

      <div style="clear:both;"></div>
      <div class="sorting_panel profile ui grid">
      <!-- nested form從這裡開始 -->
      <%= f.simple_fields_for :profile_pictures do |sub| %>
        <%= render 'profile_fields', f: sub %>
      <% end %>
      <!-- nested form結束 -->
      </div>
    </div>
    <div style="clear:both;"></div>
  </div>
<% end %>

app/views/admin/products/_picture_fields.html.erb
<div class="nested-fields ui three wide column">
<i class="move icon" style="margin: 10px 0px; cursor: move;"></i>
<%= f.input :image, :as => :image_preview, :input_html => {:preview_version => :thumb,  :onchange => "readURL(this);" } %>
<%= f.hidden_field :seq %> <!-- spec的detail欄位 -->
<%= link_to_remove_association "移除", f, { data: {confirm: '要刪除嗎?'}, class: 'ui red button', style: "height: 36px" } %>
</div>

app/views/admin/products/_product_fields.html.erb
<div class="nested-fields ui five fields">
<i class="sort icon" style="margin: 10px 0px; cursor: move;"></i>
<%= f.input :size, wrapper: :input_labeled, label: "尺碼", placeholder: "尺碼 S/M/L" %> <!-- spec的name欄位 -->
<%= f.input :color, wrapper: :input_labeled, label: "顏色", placeholder: "顏色 紅/藍/綠" %> <!-- spec的detail欄位 -->
<%= f.input :qty, wrapper: :input_labeled, label: "數量", placeholder: "數量" %>
<%= f.input :itemcode, wrapper: :input_labeled, label: "商店貨號", placeholder: "商店貨號" %>
<%= f.hidden_field :seq %> <!-- spec的detail欄位 -->
<%= link_to_remove_association "移除", f, { data: {confirm: '要刪除嗎?'}, class: 'ui red button', style: "height: 36px" } %>
</div>

app/views/admin/products/_profile_fields.html.erb
<div class="nested-fields ui three wide column">
<i class="move icon" style="margin: 10px 0px; cursor: move;"></i>
<%= f.input :image, :as => :image_preview, :input_html => {:preview_version => :thumb,  :onchange => "readURL(this);" } %>
<%= f.hidden_field :seq %> <!-- spec的detail欄位 -->
<%= link_to_remove_association "移除", f, { data: {confirm: '要刪除嗎?'}, class: 'ui red button', style: "height: 36px" } %>
</div>

app/views/admin/products/edit.html.erb
<%= render :partial => 'admin/products/form' %>

app/views/admin/products/index.html.erb
<%= 
  content_tag(:div, class: "ui inverted top attached menu large") do 
    concat(content_tag(:div, '商品維護', class: "item header"))
    concat(content_tag(:a, '新增', class: "active item right button", href: new_admin_product_path))
  end
%>
<%= grid(@products_grid) do |g|

  g.blank_slate  do
    content_tag(:div, "There are no records", class: "ui tertiary segment") 
  end
  
  g.column class: 'left aligned one wide' do |product|
    image_tag(product.main_pictures.first.image.thumb.url) unless product.main_pictures.blank?
  end

  g.column name: '商品名稱', attribute: 'caption', auto_reload: false, filter: false

  g.column name: '定價', attribute: 'unit_price', auto_reload: false, filter: false

  g.column name: '售價', attribute: 'sale_price', auto_reload: false, filter: false

  g.column name: '成本', attribute: 'cost', auto_reload: false, filter: false

  g.column name: '貨號', attribute: 'itemcode', auto_reload: false, filter: false

  g.column name: '數量', class: 'center aligned one wide' do |product|
    product.sub_products.map{|product| product.qty}.sum
  end

  g.column name: '規格', class: 'cen aligned two wide' do |product|
    product.sub_products.collect{|product| "#{product.size} #{product.color}"}.to_sentence(:two_words_connector => ' , ')
  end

  g.column name: '分類', class: 'cen aligned two wide' do |product|
    product.categories.collect{|category| category.caption}.to_sentence(:two_words_connector => ' , ')
  end

  g.column class: 'center aligned two wide' do |product|
    content_tag(:div) do
      concat(link_to('修改', edit_admin_product_path(product), class: 'ui blue mini button'))
      concat(link_to('移除', product, method: :delete, data: { confirm: '確定要移除?' }, class: 'ui red mini button'))
    end
  end

end -%>

app/views/admin/products/new.html.erb
<%= render :partial => 'admin/products/form' %>