config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :dashboard, :groups, :categories, :products, :menus
    devise_for :users, class_name: "Admin::User", controllers: {
      confirmations: "admin/users/confirmations",
      passwords: "admin/users/passwords",
      registrations: "admin/users/registrations",
      sessions: "admin/users/sessions", 
      unlocks: "admin/users/unlocks"       
    }
    root 'dashboard#index'
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions", 
    unlocks: "users/unlocks"       
  }
  
  resources :site do
    collection do
      get 'find'
      post 'spec'
      post 'cart_add'
      post 'cart_del'
    end

    member do
    end
  end

  resources :search

  resources :shopping

  resources :myaccount

  root 'site#index'

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
    
  end

  def find
    keywords = params[:keywords]
    if !keywords.blank?
      @products = Admin::Product.all
      @products = @products.where(["caption LIKE ?", "%#{keywords}%"])
      if @products.empty?
        categories = Admin::Category.where(["caption LIKE ?", "%#{keywords}%"])
        @products = categories.first.products unless categories.first.nil?
      end
    else
      redirect_to :action => :index
    end
  end

  def show
    if !params[:id].blank?
      @product = Admin::Product.find(params[:id])
    else
      redirect_to :action => :index
    end
  end

  def spec
    if request.xhr?
      @product = Admin::Product.find(query_params[:id])
        .sub_products.select('id, product_id, itemcode, qty, size, color')
        .where(["size = ? and color = ? ", query_params[:size], query_params[:color] ]).first
      render :json => @product
    end
  end

  def cart_add
    cart.add_item(query_params)
    redirect_to site_path(query_params[:id])
  end

  def cart_del
    # if request.xhr?
      cart.del_item(params[:itemcode])
      redirect_to site_path(params[:id])
      # render :json => params[:itemcode]
    # end
  end
	
  def query_params
    params.require(:buy).permit(:id, :caption, :img, :buy_count, :item_id, :itemcode, :color, :size, :sale_price)
  end
end

app/helpers/site_helper.rb
module SiteHelper
  
end

app/views/site/_item_fields.html.erb
<div class="green card">

  <% if !f.main_pictures.limit(1).offset(1).blank? %>
  <div class="ui slide masked reveal image">
    <img src=<%= f.main_pictures.first.image.medium.url %> class="visible content" >
    <img src=<%= f.main_pictures.limit(1).offset(1).first.image.medium.url %> class="hidden content" >
  </div>
  <% else %>
  <div class="ui image">
    <img src=<%= f.main_pictures.first.image.medium.url %> class="visible content" >
  </div>
  <% end %>
  <div class="content">
    <div class="ui header">
      <%=f.caption %>
      <div class="sub header" style="margin: 5px 0px">
        <div class="left floated">
        <del>NT$<%=f.unit_price.round %></del>
        </div>
        <div class="right floated">
        NT$<%=f.sale_price.round %>
        </div>
      </div>
    </div>
    <div style="clear:both;"></div>
    <div class="meta" style="margin-top: 10px">
      <a>規格</a>
    </div>
    <div class="description">
    <%= f.sub_products.pluck("DISTINCT size").collect{|size| size}.to_sentence(:two_words_connector => ' , ')
    %>
    <%= f.sub_products.pluck("DISTINCT color").collect{|color| color}.to_sentence(:two_words_connector => ' , ')
    %>
    </div>
  </div>
  <div class="extra content">
    <%= link_to('選購', site_path(:id => f.id), class: "ui tiny green basic button right floated") %>
    <span><i class="user icon"></i> 75 人購買 </span>
  </div>
</div>

app/views/site/find.html.erb
<% if @products.empty? %>
  <div class="ui icon message">
    <i class="shop icon"></i>
    <div class="content">
      <div class="header"> 查無此商品 </div>
      <p>請試試熱門關鍵字： 女裝、ZUZU、日本</p>
    </div>
  </div>
<% else %>
  <div class="ui four cards">
    <% @products.each do |product| %>
      <%= render 'item_fields', f: product %>
    <% end %>
  </div>
<% end %>

app/views/site/index.html.erb
  <div class="ui inverted vertical masthead center aligned segment">
    <div class="ui text container">
      <h1 class="ui inverted header">
        Imagine-a-Company
      </h1>
      <h2>Do whatever you want when you want to.</h2>
      <div class="ui huge primary button">Get Started <i class="right arrow icon"></i></div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="eight wide column">
          <h3 class="ui header">We Help Companies and Companions</h3>
          <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
          <h3 class="ui header">We Make Bananas That Can Dance</h3>
          <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
        </div>
        <div class="six wide right floated column">
          <img src="assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
        </div>
      </div>
      <div class="row">
        <div class="center aligned column">
          <a class="ui huge button">Check Them Out</a>
        </div>
      </div>
    </div>
  </div>


  <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"What a Company"</h3>
          <p>That is what they all say about us</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <img src="assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
      <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
      <a class="ui large button">Read More</a>
      <h4 class="ui horizontal header divider">
        <a href="#">Case Studies</a>
      </h4>
      <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
      <p>Yes I know you probably disregarded the earlier boasts as non-sequitor filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
      <a class="ui large button">I'm Still Quite Interested</a>
    </div>
  </div>

app/views/site/show.html.erb
<div class="ui grid">
	<div class="two wide column">
    {類似商品}
  </div>
	<div class="fourteen wide column">
		<div class="ui grid">
  		<div class="eight wide column">
        <!-- pictures -->
        <div class="fotorama" data-nav="thumbs" data-allowfullscreen="true">
          <% @product.main_pictures.each do |picture| %>
            <%= content_tag(:a, href: picture.image.medium.url) do
                concat(image_tag(picture.image.thumb.url))
              end
            %>
          <% end %>
        </div>
      </div>
  		<div class="eight wide column">
        <div class="ui vertical segment">
          <div class="ui two column relaxed grid">
            <div class="column">
              <h1 class="ui header" style="padding-top: 10px"> 
                <div class="content">
                  <%= @product.caption  %>
                  <div class="sub header"> 
                    <span style="display: block;">商品編號：</span>
                    <span style="display: block;" id="lbl_itemcode"> - </span>
                  </div>
                </div>
              </h1>
              
            </div>
            <div class="column">
              <a class="ui teal right ribbon label" style="margin-left: -10px">新貨到</a>
              <div style="text-align: right">
                <del style="display: block; margin: 10px 0px 5px 0px">$<%= @product.unit_price.round %></del>
                <div style="display: block; color: red;">
                  <span> NT </span>
                  <span style="font-size: 3em;">$<%= @product.sale_price.round %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="ui vertical segment">
          <div class="ui one column relaxed grid">
            <div class="column">
              <div class="ui teal large labels">
                <div class="product color">
                  <% for color in @product.sub_products.pluck("DISTINCT color") %>
                    <%= 
                      content_tag(:a, color, class: "ui label",  "data-value": color) unless color.blank?
                    %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="column">
              <div class="ui blue large labels">
                <div class="product size">
                  <% @product.sub_products.pluck("DISTINCT size").each do |size| %>
                    <%= 
                      content_tag(:a, size, class: "ui label",  "data-value": size)
                    %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="column">
              <a class="ui right floated mini button">查看尺寸表</a>
            </div>
          </div>
          <!-- 規格選擇 -->
        </div>
        <div class="ui vertical segment">
          <% if current_user %>
            <%= simple_form_for :buy, url: cart_add_site_index_path do |f| %>
              <%= hidden_field_tag "buy[img]", @product.main_pictures.first.image.thumb.url %>
              <%= hidden_field_tag "buy[caption]", @product.caption %>
              <%= hidden_field_tag "buy[sale_price]", @product.sale_price %>
              <%= hidden_field_tag "buy[id]", @product.id %>
              <%= hidden_field_tag "buy[itemcode]" %>
              <%= hidden_field_tag "buy[color]" %>
              <%= hidden_field_tag "buy[size]" %>
              <div class="inline fields">
                <div class="twelve wide field">
                  <label>數量</label>
                  <%= select_tag "buy[buy_count]", nil, class: "ui dropdown" %>
                </div>
                <button class="ui fluid green button" onclick="return check_buy();">放入購物車</button>
              </div>
            <% end %>
            <div class="ui icon info message" style="display: none;" id="sellout">
              <i class="help circle icon"></i>
              銷售一空
            </div>
          <% else %>
            <div class="ui warning message">請先登入</div>
          <% end %>
          <!-- 加入購物車 -->
          <!-- 數量先用下拉方式 -->
<!--             <div class="ui buttons" id="buy_group" style="margin: 5px 20px 0px 0px ">
              <a class="ui label" id="minus">+</a>
              <%# text_field_tag :buyCount, nil, disabled: :disabled, maxlength: 2, style: "margin:-1px 0px ;width: 50px" %>
              <a class="ui label" id="plus">-</a>
            </div> -->
        </div>
      </div>
    </div>

    <div class="ui vertical segment">
      <h3 class="ui dividing header"><i class="icon info"></i>產品說明及注意事項</h3>
      <%= sanitize @product.description %>
    </div>
    <div class="ui very relaxed list">
      <% @product.profile_pictures.each do |picture| %>
        <%= content_tag(:div, class: "item") do
            concat(image_tag(picture.image.url, class: "ui fluid image"))
          end
        %>
      <% end %>
    </div>
	</div>
</div>
<script type="text/javascript">
  $(function(){
    $('.product.color a:eq(0)').click();
  });
</script>