config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :dashboard, :groups, :categories, :products, :menus
    devise_for :users, class_name: "Admin::User", controllers: {
      confirmations: "admin/users/confirmations",
      passwords: "admin/users/passwords",
      registrations: "admin/users/registrations",
      sessions: "admin/users/sessions", 
      unlocks: "admin/users/unlocks"       
    }
    root 'dashboard#index'
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions", 
    unlocks: "users/unlocks"       
  }
  
  resources :site do
    collection do
      get 'find'
      post 'spec'
      post 'cart_add'
      post 'cart_del'
    end

    member do
    end
  end

  resources :search

  resources :shopping

  resources :myaccount

  root 'site#index'

end

app/views/common/_footer.html.erb
<!-- start of footer -->
<div class="ui inverted vertical footer segment" style="margin-top: 10px">
  <div class="ui container">
    <div class="ui stackable inverted divided equal height stackable grid">
      <div class="three wide column">
        <h4 class="ui inverted header">About</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Sitemap</a>
          <a href="#" class="item">Contact Us</a>
          <a href="#" class="item">Religious Ceremonies</a>
          <a href="#" class="item">Gazebo Plans</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Services</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Banana Pre-Order</a>
          <a href="#" class="item">DNA FAQ</a>
          <a href="#" class="item">How To Access</a>
          <a href="#" class="item">Favorite X-Men</a>
        </div>
      </div>
      <div class="seven wide column">
        <h4 class="ui inverted header">Footer Header</h4>
        <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
      </div>
    </div>
  </div>
</div>
<!-- end of footer -->

app/views/common/_navbar.html.erb
<script>
  $(function(){
    $('.menu .brand')
      .popup({
        popup : $('brand'),
        inline   : true,
        hoverable: true,
        position : 'bottom left',
        delay: {
          show: 300,
          hide: 800
        }
      })
    ;
    $('.menu .special')
      .popup({
        popup : $('special'),
        inline   : true,
        hoverable: true,
        position : 'bottom left',
        delay: {
          show: 300,
          hide: 800
        }
      })
    ;
  });
</script>
<div class="ui top fixed stackable menu">
  <div class="ui container">
    <%= content_tag(:a, href: root_path, class: "item") do
        concat(image_tag("logo.png", class: "logo"))
      end
    %>
    <a class="brand item">品牌<i class="dropdown icon"></i> </a>
    <a class="special item">特賣會<i class="dropdown icon"></i> </a>
    <div class="right menu">
      <div class="item">
        <div class="ui icon input">
          <%= form_tag(find_site_index_path, method: :get) do %>
            <input type="text" placeholder="Search..." name="keywords" value=<%= params[:keywords] %>>
          <% end %>
          <i class="search link icon"></i>
        </div>
      </div>
      <% if current_user %>
        <div class="ui right dropdown item">
          <i class="user icon"></i>
          <%= current_user.username %>
          <i class="dropdown icon"></i>
          <div class="menu">
          <div class="item">我的帳戶</div>
          <%= link_to('修改密碼', edit_registration_path(:user), class: "item") %>
          <%= link_to('登出', destroy_user_session_path, :method => :delete, class: "item") %>
          </div>
        </div>
        <a class="item cart">
          <i class="icon in cart large"></i>購物車
          <div class="ui top right attached red <%= "hidden" if (cart.cart_count == 0) %> label"><%= cart.cart_count %></div>
        </a>
      <% else %>
        <%= link_to('註冊', new_registration_path(:user), class: "item") %>
        <%= link_to('登入', new_session_path(:user), class: "item") %>
      <% end %>
    </div>
  </div>
</div>
<!-- brand -->
<% categories = Admin::Category.where(:description => '品牌') %>
<brand class="ui flowing popup bottom left transition hidden">
  <div class="ui <%= categories.count.humanize %> column relaxed divided grid">
    <% categories.each do |category| %>
    <div class="column">
      <h4 class="ui header">
      <%= content_tag(:a, category.caption, href: find_site_index_path(:keywords => category.caption)) %>
      </h4>
      <div class="ui link list">
        <% category.sub_categories.each do |sub| %>
          <%= content_tag(:a, sub.caption, href: find_site_index_path(:keywords => sub.caption), class: "item", style: "width: 100px") %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</brand>
<!-- special -->
<% categories = Admin::Category.where(:description => '特賣會') %>
<special class="ui flowing popup bottom left transition hidden">
  <div class="ui <%= categories.count.humanize %> column relaxed divided grid">
    <% categories.each do |category| %>
    <div class="column">
      <h4 class="ui header">
      <%= content_tag(:a, category.caption, href: find_site_index_path(:keywords => category.caption)) %>
      </h4>
      <div class="ui link list">
        <% category.sub_categories.each do |sub| %>
          <%= content_tag(:a, sub.caption, href: find_site_index_path(:keywords => sub.caption), class: "item", style: "width: 100px") %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</special>

app/views/common/_sidebar_cart.html.erb
<div class="ui right wide sidebar vertical menu">
  <div class="item">
    <h2 class="ui center aligned icon header">
      <i class="circular shop icon"></i> 
      <div class="sub header">
        採購明細
      </div>
    </h2>
  </div>
  <% cart.cart_contents.each do |key, value| %>
  <div class="item" id=<%= key %>>
    <div class="ui grid">
      <div class="four wide column">
        <img src= <%= value["img"] %> >
      </div>
      <div class="nine wide column">
        <div class="ui small header">
          <%= value["caption"] %>
          <div class="sub header">
            <div>貨號:<%= value["itemcode"] %></div>
            <div>規格:<%= "顏色(#{value['color']})" unless value['color'].blank? %>  
                    <%= "尺碼(#{value['size']})" unless value['size'].blank? %></div>
            <div>數量:<%= value["buy_count"] %></div>
          </div>
        </div>
      </div>
      <div class="three wide middle aligned column">
        <%= 
          link_to "<i class='trash icon'></i>".html_safe, cart_del_site_index_path(value), 
            method: :cart_del, data: { confirm: '確定要移除?' }, class: "ui icon red button"
        %>
      </div>
    </div>
  </div>
  <% end %>
  <% if (cart.cart_count > 0) %>
  <div class="item">
    <%= 
      link_to "前往結帳", new_shopping_path, class: "fluid ui green button"
    %>
  </div>
  <% end %>

</div>